include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    # lines_longer_than_80_chars: true

analyzer:
  exclude:
    - lib/helper/app_constant.dart
    - lib/helper/app_colors.dart
    - lib/helper/extension.dart
  language:
    # strict-inference: true
    # strict-raw-types: true
  plugins:
    - dart_code_metrics
  strong-mode:
    # implicit-casts: false
    # implicit-dynamic: false

dart_code_metrics:
  anti-patterns:
    # - long-method
    # - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - lib/helper/app_constant.dart
    - lib/helper/app_colors.dart
    - lib/helper/extension.dart
  rules:
    # - no-boolean-literal-compare
    # - no-empty-block
    # - prefer-conditional-expressions
    # - no-equal-then-else
