name: flutter_boilerplate
description: Flutter boilerplate project for faster start
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  device_info_plus: ^4.0.0
  flutter_flavor: ^3.0.3
  flutter_logs: ^2.1.5
  flutter_easyloading: ^3.0.3
  get: ^4.6.0
  google_fonts: ^3.0.1
  hive_flutter: ^1.1.0
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^4.15.2
  dependency_validator: ^3.2.0
  hive_generator: ^1.1.2
  json_serializable: ^6.2.0
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/lotties/
    - assets/images/
    - assets/fonts/
    - assets/certificates/

flutter_flavor:
  dimensions:
    android: "flutter-flavor"

  flavors:
    dev:
      android:
        name: "APP DEV"
        applicationId: "com.flutter.boilerplate.dev"
    prod:
      android:
        name: "APP"
        applicationId: "com.flutter.boilerplate"

